### ISSUE TITLE
DATA_ROOT for GEOS-Chem master

### ISSUE THREAD

**Issue by miroi** [geoschem/geos-chem-unittest#11]
Hi,

I am trying to adapt the UT/perl/UnitTest.input file for the currect GEOS-Chem master. As first thing, I do not see the directory gcgrid/data/ExtData in the currect GEOS-Chem program.

Also, the file  UT/perl/UnitTest.input is versioned, so its local modification may prevent UT updating via "git pull".

Any help, please ?

**Comment by lizziel** [comment]
The path for DATA_ROOT should be edited in file UT/perl/UnitTest.input to be the path to the data on your system. You need to download the data separately from GEOS-Chem. Please see our [wiki page on downloading shared data directories](http://wiki.seas.harvard.edu/geos-chem/index.php/Downloading_GEOS-Chem_data_directories) if you have not done this already.

The VERSION string in UnitTest.input is not used by git. You can do 'git pull' to get the latest version from GitHub regardless of what the version string is set to.
