### ISSUE TITLE
[FEATURE REQUEST] Rename Emissions Menu to UCX Menu for clarity

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem-unittest#13]
The Emissions Menu currently consists of mostly switches for UCX. We should make a new UCX Menu for clarity. Emissions should be switched on/off via the HEMCO_Config.rc file.

Currently:
```
%%% EMISSIONS MENU %%%  :
Turn on emissions?      : T
HEMCO Input file        : HEMCO_Config.rc
 => 1ppt MBL BRO Sim.?  : F
Switches for UCX        :---
 => Use CH4 emissions?  : F
 => Turn on surface BCs :---
    => CH4?             : F
    => OCS?             : T
    => CFCs?            : T
    => Cl species?      : T
    => Br species?      : F
    => N2O?             : T
 => Set initial glob MRs:---
    => strat. H2O?      : T
 => CFC emission year   : 0
```

**Comment by tsherwen** [comment]
Hello Melissa,

Just saw this email and thought I would flag that the vast majority of
these switches (and the bromine ones) have been removed in the boundary
condition pull request (linked below). I guess you realise this but thought
I would flag it in case it was useful. I agree moving the remainder to
HEMCO_Config.rc would be a good idea.

https://github.com/geoschem/geos-chem/pull/78

Cheers,

Tomas

Tomás Sherwen
<https://twitter.com/DrTomasS/>
<https://scholar.google.co.uk/citations?user=e3SmNJoAAAAJ&hl=en>
<https://publons.com/author/1359451/tomas-sherwen> [image:
tomas.sherwen@york.ac.uk] <tomas.sherwen@york.ac.uk>
<https://orcid.org/0000-0002-3006-3876>
<https://www.linkedin.com/in/tom%C3%A1s-sherwen-a6185726/>

**Comment by msulprizio** [comment]
Good point, @tsherwen! Thanks for bringing that up. We will be sure to pull in your changes before addressing this request.

**Comment by msulprizio** [comment]
As Tomas points out above, there is no longer a need for this feature after merging in  https://github.com/geoschem/geos-chem/pull/78. The Emissions Menu is reduced to:

```
%%% EMISSIONS MENU %%%  :
Turn on emissions?      : T
HEMCO Input file        : HEMCO_Config.rc
Switches for UCX        :---
 => Use CH4 emissions?  : F
 => Set init. strat. H2O: T
```
