### ISSUE TITLE
[BUG] gc_timing runs not working in 12.6.3

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem-unittest#17]
I'm setting up GEOS-Chem classic on our new Australian supercomputer (Gadi) and as part of the process was planning to run some timing tests. I've cloned the most recent version (12.6.3) and verified that I can compile and run simulations on Gadi without trouble.

However, the gc_timing simulations are failing. For these, I've created the run directory using gcCopyrundirs with the following lines specified in CopyRunDirs.input:
```
## ======= GEOS-Chem 7-day time test ==========================================
geosfp   4x5         -      gc_timing        2016070100   2016070800     -   
```

The run dies immediately with the following error message:
```
READ_INPUT_FILE: Reading input.geos
===============================================================================
GEOS-Chem ERROR: gc_timing is not a valid simulation. Supported simulations 
are: AcidUptake, Aerosol, APM, Benchmark, CH4, CO2, ComplexSOA, 
ComplexSOA_SVPOA, HEMCO, Hg, MarinePOA, MassCons, POPs, RRTMG, Standard, 
TransportTracers, Tropchem, TagCO, TagCH4, TagHg, TagO3, TO
 -> at Read_Simulation_Menu (in GeosCore/input_mod.F)
===============================================================================
```
Are timing tests no longer supported?

Or does there just need to be a fix to change what is written to the `Simulation name` line of the input.geos file? I found that manually changing that entry to `standard` lets the simulation run, but I'm not sure if it breaks anything else.

I also found that there are problems with the printTime script, which I'm guessing hasn't been updated to match the newest compilation output. To run the script without errors, I had to:
1. Change all instances of `lastbuild.mp` to `lastbuild`
2. Around line 160 (in the foreach loop), change
```
    @result = split( ':', $grep );
```
to
```
    if (index($grep, ":") != -1) {
       @result = split( ':', $grep );
    }   
    else {
       next;
    }   
```
Without #2, I was getting a lot of errors like:
```
Use of uninitialized value $result[0] in pattern match (m//) at ./printTime line 164.
```

I'm not sure if this is a fix or if it just masks an underlying problem, so I didn't want to submit it directly.

**Comment by yantosca** [comment]
Thanks for pointing this out.  There have been several updates in GC 12.6.0 regarding the run directories and Makefile.  We haven't as yet had a chance to test this.

In input.geos, changing:
```
Simulation name         : {SIM}
```
to
```
Simulation name         : standard
```
will fix that issue.  A gc_timing run is basically a standard run w/ timers on, etc.

Also in the doTimeTest* scripts, we need to change:

```
srun -c $OMP_NUM_THREADS time -p ./geos.mp
```
and similar commands to
```
srun -c $OMP_NUM_THREADS time -p ./geos
```
In GEOS-Chem 12.6.0 and later, we no longer use mp or sp.   Also to compile, we use
```
make -j4 buiild
```
instead of 
```
make -j4 mp
```
etc.  

I'll push a fix off of dev/12.7.0 unit test, and will also include your PBS script.  Stay tuned.

**Comment by yantosca** [comment]
I just did a 1-day gc-timing run on dev/12.7.0 (with commits https://github.com/geoschem/geos-chem-unittest/commit/bc458fedcff65b9100dba836afaa23cf19941cc5 and https://github.com/geoschem/geos-chem-unittest/commit/bc515d7737aa873680b92bf87db4ad32e17262be).

I ran an interactive time test for 1-day (just for validation's sake):
```
cd geosfp_4x5_gc_timing
make -j4 gcbuild TIMERS=1
doTimeTest
```

and that created the following output:

```
**************   E N D   O F   G E O S -- C H E M   **************
real 1264.01
user 6380.70
sys 59.64
# of CPUs: 6
...etc...
```
I will also take a look at the wiki documentation and update that as well for version 12.6.0 and later.

So I think we should be good to go now!  Thanks again for pointing this out.

**Comment by yantosca** [comment]
I just added your fixes for the gc_timing/printTime script in commit https://github.com/geoschem/geos-chem-unittest/commit/699cf851462fba1d3b8c9ab3dbaf24876e1d5f64.  

I used a quick (1-hour) time test to generate a log file, then used printTime to display the results:

```
GEOS-Chem 7-Model-Day Time Test Results
===============================================================================

Machine information
-------------------------------------------------------------------------------
Machine or node name: : holyjacob01.rc.fas.harvard.edu
CPU vendor            : GenuineIntel
CPU model name        : Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
CPU speed [MHz]       : 1199.951

GEOS-Chem information
-------------------------------------------------------------------------------
GEOS-Chem Version     : 12.7.0
Last commit           : Add missing entries to ExtData.rc file for GCHP
Commit date           : Tue Jan 7 10:54:52 2020 -0500
Compiler version      : gfortran 9.2.0
Compilation options   : traceback

Simulation information
-------------------------------------------------------------------------------
Simulation start date : 20160701 000000
Simulation end date   : 20160701 010000
Number of CPUs used   : 6
Total CPU time  [s]   : 449.62
Wall clock time [s]   : 107.17
CPU / Wall ratio      : 4.1954
% of ideal performace : 69.92
```
I didn't get any "uninitialized value" warnings so I think this is all set.  Again, thanks for pointing this out!!

**Comment by jennyfisher** [comment]
Great, thanks - glad this was useful!

**Comment by yantosca** [comment]
Thanks.  We can close this out now.
