### ISSUE TITLE
Makefile version number needs updating

### ISSUE THREAD

**Issue by jennyfisher** [geoschem/geos-chem-unittest#21]
The file `runs/shared_inputs/Makefiles/Makefile:` still shows `VERSION     :=12.8.0` even when v12.8.1 has been cloned as a fresh install. I assume this should be updated to match the git tag...

**Comment by lizziel** [comment]
Hi Jenny, thanks for reporting this. The Makefile is going to be retired in 13.0 so this issue of forgetting to change the version number in that file will no longer be a problem. We will instead get version number automatically from the git information of the source code repository, which is where the GEOS-Chem Classic run directories will be created starting in 13.0. Hard-coding version number is definitely problematic!

**Comment by yantosca** [comment]
I've now updated the version numbers for master (12.8.1) and dev/12.9.0.
