### ISSUE TITLE
Version number not updated to 12.1.1

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-unittest#4]
Just a minor issue:

https://github.com/geoschem/geos-chem-unittest/blob/0f18d1db4e6c733feaeeb6bab13f1612f7730d89/runs/shared_inputs/Makefiles/Makefile#L64-L66

**Comment by yantosca** [comment]
This is now fixed.  I pushed an update to the master branch today (17 Dec 2018).
