### ISSUE TITLE
A question about running 4x5_standard by Geos-chem 12.1.1?

### ISSUE THREAD

**Issue by gc13141112** [geoschem/geos-chem-unittest#6]
READ_INPUT_FILE: Reading input.geos
SPLIT_ONE_LINE: error at Nested I0, J0
Expected  2 substrs but found   1
STOP in SPLIT_ONE_LINE (input_mod.f)!
===============================================================================
===============================================================================
GEOS-Chem ERROR: SPLIT_ONE_LINE: error at Nested I0, J0
 -> at Split_One_Line (in module GeosCore/input_mod.F)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error reading the "input.geos" file!
 -> at Read_Simulation_Menu (in GeosCore/input_mod.F)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error in "Read_Simulation_Menu"!
 -> at Read_Input_File (in module GeosCore/input_mod.F)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Read_Input_File"!
STOP at GEOS-Chem (in GeosCore/main.F)
===============================================================================

**Comment by msulprizio** [comment]
It seems that you may be using an input.geos file that is not for the same version as your code directory. Please check the git history for both your code directory and unit tester directory to make sure they are for the same version (marked by tags). If necessary, update your unit tester directory and create a new run directory.

If you are confident you are using the same version for your code and run directory and are still having problems, please review our guidelines for submitting a support request and send us the files listed here: http://wiki.seas.harvard.edu/geos-chem/index.php/Submitting_GEOS-Chem_support_requests#What_do_I_need_to_include_in_my_support_request.3F.

**Comment by yantosca** [comment]
I have added a section on our "Common GEOS-Chem error messages" wiki page about this:

http://wiki.seas.harvard.edu/geos-chem/index.php/Common_GEOS-Chem_error_messages#Error_reading_the_input.geos_file

Bob Y.
